import java.awt.*;
import java.awt.event.*;
 
public class ButtonDemo extends Frame implements ActionListener
{
  Button ab, rb;           	          // ab for accept button and rb for reject button
  
  public ButtonDemo()	                  // a constructor to create frame, set the layout to frame and create GUI components
  {
    setLayout(new FlowLayout());          // frame is set to FlowLayout style of arranging buttons
 
    ab = new Button("Accept");            // convert the above reference variables into objects
    rb = new Button("Reject");   
 
    ab.addActionListener(this);	          // link the button ab with ActionListener. "this" refers ActionListener
    rb.addActionListener(this);	          // now ActionListener takes care of ActionEvent generated by ab and rb buttons
 
    add(ab);  add(rb);		          // add the buttons one-by-one to frame
 
    setTitle("Buttons by S N Rao");	  // frame creation methods
    setSize(500,500);
    setVisible(true);
  }				          // now, override the abstract method of ActionListener interface
  public void actionPerformed(ActionEvent e)     
  {
    String str = e.getActionCommand();
    
    if(str.equals("Accept"))
      System.out.println("You clicked " + str + " button, Thank you for accepting the agreement");
    else if(str.equals("Reject"))
      System.out.println("You clicked " + str + " button, Sorry for rejecting the agreement");
  }
  public static void main(String args[])
  {
    new ButtonDemo();		          // just call the constructor because all the code exists in constructor
  }
}
